### ISSUE TITLE
Cannot enable extension FreshRss FlareSolverr: server cannot write in /var/www/FreshRSS/p/api

### ISSUE THREAD

**Issue by Sonnenfleck** [ravenscroftj/freshrss-flaresolverr-extension#5]
When I try to enable the extension, I get the following error message:

`Cannot enable extension FreshRss FlareSolverr: server cannot write in /var/www/FreshRSS/p/api`

I'm guessing the extension tries to write to the running instance but can't because FreshRSS is running as a Docker image?

**Comment by amozeo** [comment]
Instead of using the container directly I used build instead of image in service definition like so:
```yaml
services:
  fresh-rss:
    build:
      context: /var/empty
      dockerfile_inline: |
        FROM freshrss/freshrss:latest
        RUN chmod 776 /var/www/FreshRSS/p/api
    # rest of service definition
```
Basically it grabs the same freshrss image and changes permission of directory that this extension tries to write to to be writable.
The permission of that directory before was 766.
